# Generated by Django 4.2.2 on 2024-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_eth_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='eth_wallet',
        ),
        migrations.AddField(
            model_name='user',
            name='ethereum_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
